version: '3.8'

services:
    dbpostgres:
        image: postgres:16-alpine
        restart: unless-stopped
        container_name: code.stack-db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - code-stack

    app:
        build:
            context: .
            dockerfile: app.dockerfile
        image: jetimob/code.stack:c2
        container_name: code.stack-app
        restart: unless-stopped
        depends_on:
            - dbpostgres
        links:
            - dbpostgres
        volumes:
            - .:/app
        working_dir: /app
        networks:
            - code-stack

    node:
        image: node:18-alpine
        container_name: code.stack-node
        volumes:
            - .:/app
        working_dir: /app
        entrypoint: /bin/sh -c "npm install && npm run dev"
        depends_on:
            - app
        ports:
            - "5173:5173"

    # servidor web
    web:
        image: nginx:1.25-alpine
        container_name: code.stack-webserver
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            - code-stack
        volumes:
            - ./localhost.conf:/etc/nginx/conf.d/default.conf

volumes:
    db-data:
        driver: local

networks:
    code-stack:
        driver: bridge
